spring:
    application:
        name: automatic-parking
    # mail
    mail:
        protocol: smtp
        host: smtp.gmail.com
        port: 587
        username: chienka0003@gmail.com
        password: yfdm azjk wlki aget
        properties:
            mail:
                smtp:
                  auth: true
                  starttls.enable: true
                  starttls.required: true
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    # thymeleaf
    thymeleaf:
        prefix: classpath:/templates/

server:
    port: 8080
    ssl:
        enabled: true
        key-store: classpath:child1.p12
#        key-store: classpath:parking.com.p12
#        key-store-password: 26012003
        key-store-password: chienkoi123
        key-store-type: PKCS12
        key-alias: parking
