spring:
  application:
    name: automatic-parking
  # mail
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: chienka0003@gmail.com
    password: yfdm azjk wlki aget
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  # thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
  datasource:
    hikari:
      maximum-pool-size: 30
  mvc:
    dispatch-options-request: true
  #cache
  cache:
    caffeine:
      spec: maximumSize=100,expireAfterWrite=5m

server:
  port: 8080
