spring:
  application:
    name: automatic-parking
  # mail
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: chienka0003@gmail.com
    password: yfdm azjk wlki aget
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  # thymeleaf
  thymeleaf:
    prefix: classpath:/templates/

server:
  port: 8080
#  ssl:
#    key-store: classpath:cert.p12
#    key-store-password: chienkoi123
#    ssl.key-password: chienkoi123
#    keyStoreType: PKCS12

